### ISSUE TITLE
Dustil's quest post-Korriban

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#1]
If you complete Korriban before getting Dustil's quest, he doesn't spawn.

**Comment by Mako88** [comment]
My thoughts on how to fix this depend on how the player dealt with Korriban:

1. If the Sith became hostile on Korriban, immediately skip Carth's dialog to the assumption you killed his son, and solve the quest the same way. Basically, in the confusion, you killed him.

2. If the Sith didn't become hostile, spawn Dustil like normal (this may already be the case...I don't remember).

**Comment by JCarter426** [comment]
Regarding point 1, I don't know if that really fixes it. It still means you automatically fail the quest just on account of your planet order, which isn't fair.
I'd say something like:
1. If you trigger Dustil but then don't finish his quest and make the Sith go hostile, you should fail the quest. (issue #4)
2. If you finish Korriban and kill Uthar, the Dustil quest will never trigger at all. This is probably the case already, so the change would be to adjust the globals so the game acts like you completed the quest with respect to anything else that checks for it.
3. If you finish Korriban but don't kill Uthar, there should be no problem with spawning Dustil on Korriban. I don't know if it happens or not either.

Uthar in specific has to be checked because Dustil mentions him repeatedly, so there's no way the quest makes sense if he's dead. It shouldn't matter whether you killed Yuthura, however.

I'd have to look into the globals, but _maybe_ it could be done.

**Comment by DarthParametric** [comment]
This is the check for spawning Jordo:

```
if(IsNPCPartyMember(NPC_CARTH) &&
   //MODIFIED by Preston Watamaniuk on May 13, 2003
   //Added a check to make sure the Sith Acadamy is not closed before spawning in Jordo.
   GetGlobalBoolean("KOR_END_HOSTILE") == FALSE &&
   GetGlobalBoolean("K_MESS_CARTH") == FALSE &&
   GetGlobalNumber("K_CURRENT_PLANET") != 30 &&
   GetGlobalNumber("KOR_DANEL") == 1)
```
So number 2 should already be the status quo and it seems like number 3 should also work under vanilla conditions. So my read on it is that everything is already working as intended. If you don't spawn Jordo before finishing Korriban and/or do Korriban last, you are out of luck. I think it's fine how it is. If you do Korriban first well then it sucks to be you.
