### ISSUE TITLE
Security spikes

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#11]
Security spikes don't work.

**Comment by JCarter426** [comment]
[This should take care of it.](https://deadlystream.com/files/file/1439-jcs-security-spikes-for-k1/)

**Comment by wild-master** [comment]
In the changelog for the next release, this change is listed:
"Replaced security spikes (which did nothing before) with credits."

That's "Option B" from here:
https://deadlystream.com/files/file/1439-jcs-security-spikes-for-k1/

But "Option A" allows security spikes to work. While installing the next version of the Community Patch,, will we be able to choose Option A? If not, will we be able to uncheck the Mod called "JC's Security Spikes" while installing the Community Patch and install it separately so we could choose option A?

Why did you choose option B as the default option? Option A seems great, so I don't know why option B is needed.

**Comment by JCarter426** [comment]
We left out Option A because while I think I got them close as realistically possible, it isn't seamless and isn't really a critical fix either. AFP initially wanted to do at least something for them, though, so I came up with Option B.

But it's looking like it might be neither A nor B at this point. After releasing the mod, I realized that merchants still sock security spikes in their inventory. I'll probably do some sort of fix for my mod eventually, but I don't know if it's worth it for the Community Patch. Like you said, if people really care about it they'll probably go for Option A.

**Comment by Mako88** [comment]
Since @DarthParametric has vetoed option A for the community patch, and option B isn't really worth it, I'm going to go ahead and close this issue as "won't fix". @JCarter426 if at some point you add a fix for Option B in your mod and would like to add it to the community patch, definitely feel free to!
