### ISSUE TITLE
Manaan East Central - Ambient music track cuts out

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#157]
The ambient music track in East Central suddenly cuts out about halfway through, with a gap before restarting. The track is number 22, _mus_area_ahto_, 1:30:110 long.  @ebmar suggested that it could be the `MusicDelay` setting in the GIT. The vanilla value is 20000. West Central, which uses the same music track, is set to 120000.

**Comment by DarthParametric** [comment]
Hrm, I got this repeatedly the other day, but now I am having trouble reproducing it.

**Comment by DarthParametric** [comment]
Closing this for now, since I wasn't able to reproduce this issue on subsequent testing. Can be reopened if a repeatable cause (and a solution) is discovered.

**Comment by ebmar** [comment]
I'm sure that the long delay between BGM caused by `MusicDelay`. In every cantina module they have 0 with the value, that's why we don't hear gap between transition. Some area module even have like 120000. A "fix" would be changing the value to 0, but that would be a subjective change, I think. Sometimes it works when the music comes late, though some times they don't.
