### ISSUE TITLE
Stunt modules allow party selection

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#196]
(reported by 134340Goat)

It seems that stunt modules are generally set to be escapable, and with some quick clicking can allow the player access to the party selection screen as the cutscene starts, when they normally shouldn't be able to. One example is STUNT_51a (the Dodonna and Vandar "Bastila is using her battle meditation against us!" scenem right after the duel with Bastila or the three Dark Jedi mooks).

This could potentially be fixed by editing the stunt module ARE files. However, there are so many of them that I don't know if it's worth it for us.

**Comment by DarthParametric** [comment]
We are already editing some of those, including at least one of the Dodonna ones. We can at least add it to any existing edits we are doing, although that's obviously somewhat half-assed.

**Comment by DarthParametric** [comment]
So it seems like the candidates are:

STUNT_50a - `There - a break in the Sith formations! Green squadron, move in!`
STUNT_51a - `I have - but never from the Sith. It's almost as if... No! Bastila is using her Battle Meditation against us!`

The other two (LS and DS versions) later Dodonna stunt modules fire after defeating Malak, so they shouldn't really matter since the game is over at that point. I don't think editing two stunt modules is particularly egregious.
