### ISSUE TITLE
Mod candidates

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#20]
### Permission Pending:
- [ ] [Party Model fixes and HD Bastila](https://deadlystream.com/files/file/1273-party-model-fixes-and-hd-bastila/) Tier 2/3

### Approved:
- [x] [JC's Minor Fixes for K1](https://deadlystream.com/files/file/1333-jcs-minor-fixes-for-k1/) Tier 1/2
- [x] [Endar Spire Hull Repairs](https://deadlystream.com/files/file/1357-endar-spire-hull-repairs/) Tier 1
- [x] [K1 Lite Upgrader](https://deadlystream.com/files/file/1291-k1-lite-upgrader/) Tier 2 with possible Tier 3 extension - see #22 
- [x] [Female Armour Collar Fix](https://deadlystream.com/files/file/1425-female-armour-collar-fix) Tier 1 (maybe Tier 2)
- [x] [K1 Faster Scuba](https://deadlystream.com/files/file/1297-k1-faster-scuba/) Tier 3
- [x] [Sith Soldier Texture Restoration](https://deadlystream.com/files/file/1289-sith-soldier-texture-restoration/) (Including Sith soldiers on Korriban) Tier 3
- [x] [JC's Dense Aliens for K1](https://deadlystream.com/files/file/1290-jcs-dense-aliens-for-k1/) Tier 3

### Denied:
- [x] [JC's Supermodel Fix](https://deadlystream.com/topic/6617-modjcs-supermodel-fix-for-k1/) (compatibility issues)
- [x] [Repeating blaster attacks restoration](https://deadlystream.com/files/file/1405-repeating-blaster-attacks-restoration/) (permission not given)
- [x] [K1 Twi'lek Male 3D Ears](https://deadlystream.com/files/file/1430-k1-twilek-male-3d-ears/) 
- [x] [Bacca's Sword Description Extended](https://deadlystream.com/files/file/1433-bacas-sword-description-extended/) (Rejected on the grounds of being too messy to implement, and not really within the mod's scope)
- [x] [JC's Vision Enhancement for K1](https://deadlystream.com/files/file/1402-jcs-vision-enhancement-for-k1/) (Rejected due to K1R incompatibility. We can revisit it at a later date.

**Comment by JCarter426** [comment]
Here's a list of mods that are being considered for the new version of the Community Patch. First post will be edited to move the candidates to different categories as the situation changes.

It might be more appropriate to push each mod to their own issues in future if we end up using this a lot, but for now this is sort of a temporary measure per request by Sniggles so he doesn't forget because anything that doesn't go in the community patch will probably go in his builds.

**Comment by Mako88** [comment]
I requested permission for the nominated mods, and moved them in the comment. I personally think JC's Vision Enhancements and his Dense Aliens should be included, so I went ahead an moved them to "Approved". If there's any debate, that can be changed.

Regarding the Twi'Lek ears, I very much think it should be included, however a couple people mentioned in the comments of the mod that the ears aren't very round, and also that the neck clips through medium and heavy armor. Maybe instead of just using the mod, one of you could recreate an improved version of it with those fixes? If so, I would still want to credit the author of the mod with the idea, and let him know what we did.

**Comment by DarthParametric** [comment]
Since RedRob is basically MIA and release of v1.8 is imminent, I'm going to call this done.
