### ISSUE TITLE
Kashyyyk Great Walkway - Party trigger badly positioned

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#204]
It is quite likely that, while the party is engaged with the Kinraths just after entering the Great Walkway on Kashyyyk for the first time, one of the party members (in my case, it was Mission) will start a conversation.

I have moved that trigger so that this won't happen as easily but perhaps more can be done in terms of making the whole scene more believable. In fact, why aren't the turrets outside the gate already shooting the Kinraths and how could those creatures not have engaged with the patrol of Captain Dehno just a few yards behind them? It would make more sense to remove those creatures altogether.

**Comment by DarthParametric** [comment]
This is paired with #156 

Removing the Kinrath is not an option, since that will change the balance of the level. They could possibly be moved further back, although that might put them too close to later encounters. Alternatively, they could be set to passively remain in place rather than patrol and made to attack via a trigger. Assuming they could be moved though, the Czerka encounter could be pushed further away from the gate which should solve both issues.
