### ISSUE TITLE
Questionable loot drops

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#210]
Reported by djh269:
> Korriban Sith Torturer loot change: 
> - He originally drops a green crystal, which made no sense, so I have changed this to red.
> 
> Jedi Masters loot change: 
> - The jedi corpse in the last module on Tatooine originally has a Jedi Master Robe and a Blaster Rifle, I've changed the Blaster Rifle to a Blue Lightsaber.

I'm wary of doing anything to the green crystal because it's one of only three in the game and I can't think of a better place for it on Korriban. I also think it would be overdoing it to add a lightsaber drop, but it should be possible to remove the blaster from the Jedi and send it over to the chewed Twi'lek corpse instead with a script.

===========================================

- [x] A Jedi corpse in the Tatooine Eastern Dune Sea Krayt cave has a blaster. Should be moved to a different corpse.
- [x] The purple and Opila crystals in the Krayt cave would make more sense being found on the Jedi corpse than in rubble placeables.
- [x] The green lightsaber crystal available in the Korriban Academy is dropped by one of the Sith. Would make more sense being found on a Jedi corpse in the Shyrack Caves.

**Comment by DarthParametric** [comment]
Aren't there Jedi corpses in the Shyrack caves? They got sneak attacked by a Terentatek while they were busy making out. You could add the green crystal to the Qel-Droma Robes drop.

**Comment by JCarter426** [comment]
I hadn't thought of that. That could work.

**Comment by DarthParametric** [comment]
Replaced the generic treasure OnHearbeat for the Jedi corpse in the Krayt cave to move the blaster. 

Set the droppable flag on the torturer's green crystal to false, and added a green crystal to the Qel-Droma Robes corpse. I suppose that technically this means additional loot for DS characters that otherwise would not normally get the green crystal, but I don't think that really poses a balance issue given that colour crystals don't have any stats and are only worth a few hundred credits.

**Comment by ancient-animal** [comment]
>The jedi corpse in the last module on Tatooine originally has a Jedi Master Robe and a Blaster Rifle, I've changed the Blaster Rifle to a Blue Lightsaber.

I've always thought the dead Jedi was given a blaster intentionally by the creators of this game. I thought the creators wanted people to think he was different because he wanted to use a blaster instead of a lightsaber. I thought he was smarter than normal Jedi because he wanted to attack his enemies with a ranged weapon since he was rightfully worried about accidentally slicing off his own limbs with the laser sword. I remember enjoying thinking about that possibility of the smarter-than-usual Jedi when I played this game a long long time ago.

I won't force you to revert the change. I just want to share my opinion.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] Super minor thing, but since we have already moved the Jedi robe in the Krayt cave, it might also make sense to move the purple crystal in the nearby rubble placeable to the same corpse as well. Makes more sense that way.

**Comment by ZeldaTheSwordsman** [comment]
> 1.9.0 beta test observations:
> 
>     * [x]  Super minor thing, but since we have already moved the Jedi robe in the Krayt cave, it might also make sense to move the purple crystal in the nearby rubble placeable to the same corpse as well. Makes more sense that way.

No, not necessarily. The crystals in the rubble have formed within the rocks (perhaps even been what the Jedi came looking for), or perhaps been carried by dead companions buried in said rubble. Or even scattered from people's stuff as they were mauled. Just because they're Jedi-adjacent items doesn't mean they need to be duct-taped to a Jedi's person any time they show up outside a crystal cave. And from a gameplay perspective, putting the crystals in the rubble piles rewards players for searching thoroughly and not just checking the obvious corpses.

> Reported by djh269:
> 
> > Korriban Sith Torturer loot change:
> > 
> > * He originally drops a green crystal, which made no sense, so I have changed this to red.
> > 
> > Jedi Masters loot change:
> > 
> > * The jedi corpse in the last module on Tatooine originally has a Jedi Master Robe and a Blaster Rifle, I've changed the Blaster Rifle to a Blue Lightsaber.
> 
> I'm wary of doing anything to the green crystal because it's one of only three in the game and I can't think of a better place for it on Korriban. I also think it would be overdoing it to add a lightsaber drop, but it should be possible to remove the blaster from the Jedi and send it over to the chewed Twi'lek corpse instead with a script.
> 
> ===========================================
> 
>     * [x]  A Jedi corpse in the Tatooine Eastern Dune Sea Krayt cave has a blaster. Should be moved to a different corpse.[x]  The purple and Opila crystals in the Krayt cave would make more sense being found on the Jedi corpse than in rubble placeables.[x]  The green lightsaber crystal available in the Korriban Academy is dropped by one of the Sith. Would make more sense being found on a Jedi corpse in the Shyrack Caves.

 Regarding the green crystal... any reason it can't have come from one of the torturer's victims? Or even just be a leftover from when he changed his blade color after defecting?

Moving the blaster makes sense, the rest seems unnecessary and a product of overly-narrow thinking.
