### ISSUE TITLE
Twi'lek Czerka Officer on Kashyyyk doesn't resume walking after being talked to

### ISSUE THREAD

**Issue by Mako88** [KOTORCommunityPatches/K1_Community_Patch#23]
Reported here: https://deadlystream.com/topic/6923-kotor-manaan-docking-bugs/

When you talk to the Twi'lek Czerka officer walking around the Ebon Hawk on ~Manaan~ Kashyyyk, he won't continue walking after you finish the conversation

**Comment by DarthParametric** [comment]
Might be lacking a proper OnDisturbed or OnDialogueEnd script in his UTC perhaps? I'm not seeing a UTC for a Twi'lek Czerka officer in the Manaan Docking Bay though.

**Comment by DarthParametric** [comment]
I can see three Twi'lek Czerka Liaison Officers - kas22_xglobal_01/02/03 - all of which lack a OnDialogueEnd script, but otherwise appear to be using generic scripts. They all share the same dialogue. Not sure which is the Twi'lek in question, or whether whether all of them need the fix (or what happens when adding it to those that don't patrol).

**Comment by DarthParametric** [comment]
Adding the generic k_def_endconv script to the kas22_xglobal_01/02 UTCs as the OnDialogueEnd resolves the patrolling issue for both.
