### ISSUE TITLE
Korriban Tomb of Marka Ragnos - Rogue Assassin Droid turns hostile if extra stealth belts are in inventory

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#280]
The script that fires when you enter the droid's chamber is meant to ensure that party member 0/the player is wearing a stealth belt. However, it doesn't recognise the Baragwin Stealth Unit, since that was from the Yavin DLC and, more importantly, it will fail the check if any extra unequipped belts are left in the inventory (even if you have a suitable belt equipped).

Another interesting quirk is that since the game has no script function to check if an object is in stealth, you only need to have an appropriate belt equipped in order to pass the check. You don't actually need to be in stealth.

Vanilla script (it made a few unused object declarations, so I have left those out):
```
#include "k_inc_utility"

void SetFlag(int nState) {
	UT_SetPlotBooleanFlag(OBJECT_SELF, SW_PLOT_BOOLEAN_01, nState);
}

int GetFlag() {
	return UT_GetPlotBooleanFlag(OBJECT_SELF, SW_PLOT_BOOLEAN_01);
}

void main() {
	
	if ((GetFlag() == FALSE))
	{
		object oPC = GetFirstPC();
		object oPM0 = GetPartyMemberByIndex(0);
		object oBelt06 = GetItemPossessedBy(oPC, "G_I_BELT006");
		object oBelt07 = GetItemPossessedBy(oPC, "G_I_BELT007");
		object oBelt08 = GetItemPossessedBy(oPC, "G_I_BELT008");
		object oBelt10 = GetItemPossessedBy(oPC, "G_I_BELT010");
		object oBeltGeno = GetItemPossessedBy(oPC, "Geno_stealth");
		object oBelt06b = GetItemPossessedBy(oPM0, "G_I_BELT006");
		object oBelt07b = GetItemPossessedBy(oPM0, "G_I_BELT007");
		object oBelt08b = GetItemPossessedBy(oPM0, "G_I_BELT008");
		object oBelt10b = GetItemPossessedBy(oPM0, "G_I_BELT010");
		object oBeltGenob = GetItemPossessedBy(oPM0, "Geno_stealth");
		object oPCBelt = GetItemInSlot(10, oPC);
		object oPM0Belt = GetItemInSlot(10, oPM0);
		
		if (GetIsObjectValid(oPCBelt) || GetIsObjectValid(oPM0Belt))
			{
				if ((oPCBelt == oBelt06 || oPCBelt == oBelt07 || oPCBelt == oBelt08 || oPCBelt == oBelt10 || oPCBelt == oBeltGeno) ||
				(oPM0Belt == oBelt06b || oPM0Belt == oBelt07b || oPM0Belt == oBelt08b || oPM0Belt == oBelt10b || oPM0Belt == oBeltGenob))
					{
						UT_SetPlotBooleanFlag(OBJECT_SELF, SW_PLOT_BOOLEAN_02, TRUE);
					}
			}
		AssignCommand(oPC, ClearAllActions());
		NoClicksFor(0.7);
		DelayCommand(0.5, UT_NPC_InitConversation("k38a_assassindrd", "", OBJECT_INVALID));
		SetFlag(TRUE);
	}
}
```

The script seems an odd way to go about it. Surely doing a `GetTag` of the item in the belt slot would be a better approach? That said, I'm not sure why it fails when you have a valid belt equipped, but other belts in the inventory.

**Comment by DarthParametric** [comment]
This seems to work OK:

```
#include "k_inc_utility"

void main() {
	
	if (!UT_GetPlotBooleanFlag(OBJECT_SELF, SW_PLOT_BOOLEAN_01))
		{
			object oPM0 = GetPartyMemberByIndex(0);
			object oEquipped = GetItemInSlot(INVENTORY_SLOT_BELT, oPM0);
			string sBelt = GetTag(oEquipped);
			string sBaragwin = "G1_I_BELT001";
			string sDampening = "G_I_BELT006";
			string sAdvanced = "G_I_BELT007";
			string sEriadu = "G_I_BELT008";
			string sGenerator = "G_I_BELT010";
			string sGeno = "Geno_stealth";
			
			if (GetIsObjectValid(oEquipped))
				{
					if (sBelt == sBaragwin || sBelt == sDampening || sBelt == sAdvanced || sBelt == sEriadu || sBelt == sGenerator || sBelt == sGeno)
						{
							UT_SetPlotBooleanFlag(OBJECT_SELF, SW_PLOT_BOOLEAN_02, TRUE);
						}
				}
			
			NoClicksFor(0.7);
			AssignCommand(oPM0, ClearAllActions());
			UT_SetPlotBooleanFlag(OBJECT_SELF, SW_PLOT_BOOLEAN_01, TRUE);
			DelayCommand(0.5, UT_NPC_InitConversation("k38a_assassindrd", "", OBJECT_INVALID));
		}
}
```

**Comment by Salk73** [comment]
DP,

I'm at the moment tackling the Marka Ragnos tomb and I was wondering if it may still be inside the scope of K1 CP to make the guard droids behavior more credible and the whole scenario generally more credible.

There are three issues I see here.

1) The game considers any stealth unit belt to be valid to avoid an immediate fight with the assassin droid if party member 0 is wearing it upon entering the chamber

2) The guard droids are hostile even if party member 0 is wearing a stealth belt (as mentioned above)

3) Combat with the assassin droid can be avoided if party member 0 is wearing a stealth belt but that requirement weirdly enough doesn't extend to other party members producing a glaring inconsistency

What I would like to see is:

1) An amendment of all stealth belt descriptions to mention they have sound dampening capability except for the most basic model (Stealth Field Generator - _g_i_belt010_)

2) A change in the guard droids script so that they would turn hostile only if party member 0 is not equipped with one valid stealth belt

3) Extend stealth belt requirement to each party member with the exception of HK-47 and T3-M4 (they are droids after all so they can be somewhat excused)

Thoughts?

**Comment by DarthParametric** [comment]
Sounds like something for a 3rd party mod.

**Comment by Salk73** [comment]
DP,

I have been overhauling the whole thing for my own project but I can at least tell you that there is something that should be part of K1 CP. Namely we should either swapped [Repair] with [Computer] at #15819 or change the sub1 function used in the k38a_drd_repairs.ncs because it checks for Computer Skill rather than Repair Skill. If you like to go for the latter then

`int1 = (sub1(nGlobal, 0, GetPCSpeaker()) == 1);`

should be changed to:

`int1 = (sub1(nGlobal, 5, GetPCSpeaker()) == 1);`

**Comment by DarthParametric** [comment]
1.10.0 beta test observations:

- [ ] There's [a trigger](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M38AA_Korriban_Tomb_of_Marka_Ragnos_korr_m38aa/k38a_init_wardrd.nss) at the doorway that has the nearest war droid fire a bark string if the controlled character is not wearing a stealth belt. Like the door script, it doesn't check for the added Yavin belt.
