### ISSUE TITLE
[v1.8 Beta] Taris Upper City South - Blank line in Zelka's dialogue

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#316]
I'm not sure if this is a bug in the vanilla game or if it's related to the community patch, but either way I figured I'd better report it. There's a totally blank dialogue entry just before this line: 
![zelka_empty_vo_before](https://user-images.githubusercontent.com/42473604/67595097-ade22480-f71a-11e9-95b0-58e7d22fd024.png)

There's no subtitle/VO for couple seconds before the line pictured above plays.

**Comment by DarthParametric** [comment]
There's nothing in the DLG that would suggest a problem, and I didn't encounter any delay myself when I just tested it.

**Comment by auri0n** [comment]
I was able to reproduce is consistently - here's a short clip showing my dialogue choices:
https://www.youtube.com/watch?v=WlYdV72a77Q
P
you're probably safe to skip to 1m10s or so into the clip.

**Comment by DarthParametric** [comment]
I am still unable to reproduce the issue on my end. Following the same choices I don't get any delay.

There is a blank reply node (R103) in between the "Thank you for keeping my secret.." and "I'm afraid there is nothing more anyone can do for these soldiers..." lines that has a Delay of 0 instead of -1.  You only get that when choosing the "Don't worry. Your secret is safe with me." response, since it adds in that extra line. That might be causing the problem, although I see that a number of other blank reply nodes also have 0 as well. I can't test it, since I don't get the problem, but try this:

[tar02_zelka021.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3775592/tar02_zelka021.zip)

**Comment by auri0n** [comment]
The delay is still there, but thankfully this isn't a terribly important issue lol. Who knows what's causing it.
