### ISSUE TITLE
Unknown World Temple Interior - Dialogue/fight with Sith Master can interrupt fight with Dark Jedi

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#325]
I forgot to take a screenshot/video of this one, but hopefully you know what I'm talking about. You know, the guy who tells you how tired he is of practicing with droids. Anyway, to the point: It seems like it's pretty common for his encounter to begin while you're fighting the two Dark Jedi who recognize you as Revan. Normally this wouldn't be a problem, but it can be pretty clunky since his encounter starts with a cutscene and dialogue (which allows the two Dark Jedi to butcher your party).

**Comment by DarthParametric** [comment]
Hrm. How are you managing that? You would have to run into his room presumably, and that's assuming the door was already open due to slicing a computer terminal somewhere, otherwise you'd have to manually open it. 

I guess the trigger that fires the Dark Jedi convo could close and lock his door until after they are dead.

**Comment by auri0n** [comment]
> I guess the trigger that fires the Dark Jedi convo could close and lock his door until after they are dead.
Maybe, but his training room can be entered through two different doors (I think), so that could introduce some problems. It seemed like he opened the door himself after I used force wave on the two Dark Jedi. Could it be that he's not really being spawned in as neutral?

**Comment by DarthParametric** [comment]
No, his room can only be entered from the Dark Jedi's room. The Dark Jedi room has two entrances. 

The master is spawned in as `STANDARD_FACTION_NEUTRAL`, so he shouldn't be opening the door himself. 

As an aside, the master's opening script sets `PARTY_AISTYLE_PASSIVE` which is why they get offed by the Dark Jedi.

**Comment by auri0n** [comment]
That's good to hear - locking his door until the others are dead should be fine, then.

**Comment by DarthParametric** [comment]
Additional issue - it seems there is a party jump via the OnOpen, but the fade-out happens after the jump.

**Comment by DarthParametric** [comment]
Potential triggers issues with the master's door, reported [here](https://old.reddit.com/r/kotor/comments/u350we/kotor_1_2_mod_builds_fully_compatible_modular_mod/ipym802/?context=3).

**Comment by DarthParametric** [comment]
I'm not able to replicate the issue of the door not unlocking. Theoretically I suppose it could happen if you manage to kill both Dark Jedi mooks in the outer room simultaneously, thereby their OnDeath events failing to unlock the door. I'll have to create a kill script to test it, since it seems like an extreme edge case for it to occur organically.

On a different note, regarding the subsequent master encounter:

- [ ] Jolee and Juhani need an added `GN_DetermineCombatRound` at the end of the master intro cutscene to prevent them standing around watching.
- [ ] The master's initial zapping of the droid seems to have some timing issues. The VFX fires too soon, while he is still in an idle pose, and continues past when he has stopped the casting animation and reverted back to an idle pose.
