### ISSUE TITLE
Taris North Apartments - Sith Commander plays spurious animation when the attack starts

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#326]
This is very minor but I thought of reporting it anyway.

If the party enters the room while the Sith are searching they attack after a brief conversation. The commander moves forward but at a certain point he plays the get low animation (10) which is used when searching by all the three Sith soldiers but only seems to be played one last time by the Sith Commander when they are hostile

**Comment by DarthParametric** [comment]
They all use the same OUD, which gets signalled to turn them hostile, and the commander is the first one signalled, so not sure what the specific issue is there, assuming it is repeatable.

**Comment by Salk73** [comment]
I uploaded a video for you to see so that you can check for yourself: https://youtu.be/ckuZtTEdMfE

**Comment by DarthParametric** [comment]
It doesn't really make any sense. The trigger that fires when entering the apartment that starts the convo should flag their local booleans to stop searching. Their action stacks should have been cleared, and the OnHeartbeat event making them search shouldn't even trigger once they have been set to `STANDARD_FACTION_HOSTILE_1`.  

I suppose it would be worth trying to directly set them hostile in the attack script that fires at the end of the DLG, rather than just signalling their OUDs like the vanilla version does. Try this and see if it makes any difference:

[k_ptar_sithatk.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3818115/k_ptar_sithatk.zip)

**Comment by Salk73** [comment]
I can confirm your solution works perfectly. This can be closed.

Thanks, DP.
