### ISSUE TITLE
Zaalbar's model has a visible gap between the torso and head

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#395]
Against certain backgrounds, you can see a gap between the separate head and torso meshes of Zaalbar's body model due to backface culling. Probably the most exacerbated example is here in front of the forcefield in the Taris sewers (much more obvious in-game):

![Zaalbar0065](https://user-images.githubusercontent.com/46890653/84587678-aff12300-ae64-11ea-93b9-4939960f5725.png)

But it is also visible to a lesser degree at other times, primarily in dialogue when there is a close-up camera.

I have a fix for it, adding a plug mesh to the hole in the top of the torso, but current issues with the model tools (i.e. destroying vanilla vertex normals) make it impractical to implement.

**Comment by RedRob41** [comment]
I think that I have fixed this issue in my 4x mod (its been awhile, so my memory is fuzzy). Let's see, my spreadsheet says "upscaled with touch ups; many UVW edits; texture fix all seams; paint & UVW fix teeth; recreate alpha channel transparency based on final HD texture" but I think that I also adjusted the xyz around the neck by snapping them to the body vertexes, then running it through Taina's replacer. When I open my old .max file, I can't see the gap.

Some of the other fixes I made were to the teeth, so that the crowns of the molars have detail; inside of the mouth has the shadows at the back instead of next to the lips; added more alpha channel areas for hair punchthrough; fixed the seams where the hair on the front of the face meets the back of the head.

I also changed the palms of the hands. The new uvw map doesn't work perfectly with the vanilla texture, but on my own, I painted fingers, thumb, palm & nails.

You're welcome to it if you like. If you prefer to make it more like the vanilla texture, you can always extract the xyz coordinates and apply them to the original model.
