### ISSUE TITLE
Xor doesn't interact properly.

### ISSUE THREAD

**Issue by Yulaw9460** [KOTORCommunityPatches/K1_Community_Patch#397]
First of all, when encountering him the second time with his henchmen, he doesn't trigger the conversation with Juhani in the party with the following battle. For that to happen, I have to travel to another planet. In my current game that means that I've got a passive Xor with two Selkath goons standing outside the Ebon Hawk on Manaan from when the interaction failed the first time.

And they are... Doing. Squat. Nothing. Zilch.

When I get to the other planet, not one, but TWO Xors spawn each with two henchmen. In this run that's Tatooine. I kill them off, have the conversation with one of them, he dies... and the other wounded Xor is still standing there. Enjoying the view as Xor on Manaan.

**Comment by DarthParametric** [comment]
I assume you are using K1CP?

**Comment by ancient-animal** [comment]
I have save files that can reproduce this glitch well.

I am playing the version of this game from GOG.com that shows this for the version number: **Internal Update (29 May 2019)**

I am using ONLY these mods:
K1 Community Patch (version 1.8.1): https://deadlystream.com/files/file/1258-kotor-1-community-patch/
JC's Security Spikes for K1 (version 1.2): https://deadlystream.com/files/file/1439-jcs-security-spikes-for-k1/

I've attached three saves to this message, as a ZIP archive.

If you start the file that says "Game 95", you can walk around in the same area for a few seconds to make Xor appear during his first confrontation. NOT the fight, I mean just the first meeting.

Immediately after, I went to Korriban and talked to the guard of the Academy to make "Yuthura Ban" appear in the Cantina, and saved the game as a save called "Game 134". If you start this file, you can enter the building, and Yuthura will be there to speak to, but you could ignore her and walk all the way back to the spaceship and you will realize that the confrontation with "Xor" WILL work correctly.

After I created the "Game 134" file and noticed that it caused Xor to appear correctly, I RELOADED this "Game 134" file and SPOKE to Yuthura to make her bring me to the Academy, then I quickly rushed through the necessary conversations and walked back to the previous area, right before entering the building that leads to my spaceship, and I save this progress as a file called "Game 135".

If you start "Game 135", you will appear at the same starting position as the file called "Game 134". You can enter the building and walk all the way back to the ship, and you will notice Xor standing there. His conversation WON'T start. With this "Game 135" file, you could fly back to Manaan, then exit the ship with Carth and Juhani, and realize that you CAN fight Xor and kill him, and the quest will be completed correctly in the Journal. Then, you could fly back to Korriban, exit the ship with Carth and Juhani, and realize that the PREVIOUS Xor will STILL be standing there with his two friends.

[saves to help K1 Community Patch team - Issue 397.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/5645844/saves.to.help.K1.Community.Patch.team.-.Issue.397.zip)

**Comment by DarthParametric** [comment]
`K_XOR_AMBUSH` is set to 1, which is why the convo doesn't initiate. The OnPerceived event from his UserDefine script:
```
    else if(nUser == 1002) // PERCEIVE
        {
            int nGlobal = GetGlobalNumber("K_XOR_AMBUSH");
            
            if (nGlobal == 1)
                {
                    NoClicksFor(1.2);
                    DelayCommand(1.0, ActionStartConversation(GetFirstPC(), "", FALSE, CONVERSATION_TYPE_CINEMATIC, TRUE));
                }
        }
```
Presumably this causes the added K1CP scripts to subsequently spawn him again which then increments the global.

**Comment by DarthParametric** [comment]
Modifying Xor's UserDefine script to send messages to the PC on various events (including heartbeat) elicits no response, which is odd. He seems to be completely broken.

**Comment by DarthParametric** [comment]
Proposed fixes:

Edit `k_kas_xorattack` (spawn-in trigger OnEnter) to gate it to the PC being the entering object. Additionally, add a delay between the initial spawn-in of Xor and thugs before triggering the cutscene. Possibly the lack of a delay causes the issue in certain cases because the NPCs don't exist by the time the DLG tries to reference them. The delay will necessitate a fade-out to mask the spawning, but there may need to be a check for Juhani being in the party. Most of the DLG nodes have a built-in fade-in, but there is also a bark bubble for when Juhani isn't present which would require a scripted fade-in before initiating the DLG. Alternatively, it could just be changed to only spawn them when Juhani is present, which probably makes more sense.

Edit `k_kas_xor_user`, Xor's UserDefine script, to gate the OnPerception event to the PC being visible and also have the invisible placeable restart the conversation. The vanilla version has Xor attempt to initiate the conversation himself, but his UTC has no DLG attached. This is likely the cause of the issue with him becoming unresponsive after being defeated, presumably when he is defeated first before the thugs. Defeating him last should work since that route has the placeable trigger the DLG correctly.

These scripts are per-module rather than global, but a cursory examination suggests they are all the same.

**Comment by DarthParametric** [comment]
Xor's OUD needs a minor tweak to reset his faction rep properly when he is the last man standing.

**Comment by DarthParametric** [comment]
1.10.0 beta test 2 observations:

The change to Xor's OnDeath event, triggering a Juhani conversation, doesn't always work as intended. Since it fires her standard DLG, it will use the first available branch, not necessarily the one related to Xor's death. Either needs to be removed or switch to a custom DLG with just the two Xor-related branches.
