### ISSUE TITLE
Leviathan Command Deck/Bridge - 3 space suits better than one

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#412]
This is a minor nitpicking on my part, feel free to ignore it if you think it's silly, DP.

While it makes sense in Manaan that there is one single Water Suit since it's just the protagonist going out into the ocean, it is not so for the Leviathan where in the armory there is a single Space Suit available but a party of three is wearing one each.

I was wondering if it might be possible to add two non interactive ones which would be destroyed together with the existing one.

Additionally, even after picking up the Space Suit, the door that takes the party out still says "Locked" when clicked on despite loading the next area. I suggest (if possible) to remove the "Locked" from that door upon acquiring the Space Suit.

**Comment by DarthParametric** [comment]
It's added content, but not particularly egregious. We can just add a couple of static ones and edit the OnUsed script of the original to destroy them at the same time. 

Regarding the airlock doors, I recall them being another example of having extraneous Security icons (i.e. setting a high lock DC instead of using a key). I can't remember if I changed that when I set the other end to lock after passing through (#372 ). From memory they used the same UTD at both ends, so that may have already been resolved. Although possibly that was the internal doors, not the exterior doors. Really should be a separate issue if that is confirmed.

**Comment by Salk73** [comment]
Your fix takes care of the inner doors but in this case we are talking of the outer one: lev40_airlockout.utd.

It is indeed as you suspected, it also has a lock DC setting of 100.

**Comment by Salk73** [comment]
This is a screenshot of the armory with three suits: https://pasteboard.co/JieINzG.png

**Comment by DarthParametric** [comment]
Possible candidate for inclusion in N-DReW25's [Unofficial Tweak Pack](https://deadlystream.com/files/file/2081-unofficial-k1cp-tweak-pack/).
