### ISSUE TITLE
Leviathan Bridge - Saul cutscene

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#417]
In the cutscene I notice two issues, one of which is recurrent in many other cutscenes:

1) (recurrent) The Player head while walking to point is often not looking straight but rather angled down to one side. This kind of facing issue is something I observed many times before.

2) The light from the sun pierces almost completely unobstructed through the hull of the ship.

I made a short video (removing all module/override files): https://youtu.be/2Mc5n7uJ3H8

**Comment by DarthParametric** [comment]
The player (or NPC) head issue is that they are looking at the DLG owner, which in such instances is a placeable, usually invisible but sometimes something like a computer terminal. Regardless of what height the placeable is set in the GIT, the listener will always look at floor level. Even forcing `SetLockHeadFollowInDialog` doesn't cure it, not reliably at least, since that seemingly only stops lateral rotation, not elevation/depression. The only true resolution for this issue is to assign the DLG to an NPC. This of course can lead to other problems, since you may end up just swapping people looking at the floor to staring at the wrong NPC instead. But we have been addressing egregious examples of this behaviour as we encounter them in conversations we are editing (recent examples include #65, #66, #332). Although we made extensive edits to the Saul confrontation scene, I guess we overlooked that element. As I recall the original changes were made early on during 1.8's development, so that's probably why.  I consider this a sub-issue of #131.

As to the sun issue, I suspect that is not resolvable due to the way the engine handles VFX.

**Comment by Salk73** [comment]
Well, it seems that adding the "PLAYER" tag in the Listener field (E19) solves the problem in this case.

**Comment by Kexikus** [comment]
You can reduce the radius of the sun auroralight's flare property. That usually results in a darker glare. Or maybe there are other properties there as well that could help.

I don't really see the issue though. The sun seems to be shining through a window and admittedly has an overdone bloom/glare effect but that's probably intended to be cinematic and is something that could be seen in an actual camera as well.

**Comment by Salk73** [comment]
In my opinion the corona effect (or whatever is called) is way too much and distracting.

I realize it is mostly a matter of taste though.

**Comment by DarthParametric** [comment]
I have switched the initial scene to be initiated by Saul rather than the invisible placeable, which resolves the worst of the looking-at-floor problem. Although Bastila still seems to have a bit of Princess Diana syndrome going on. I also took the opportunity to lock Carth and Bastila's head orientation during this scene, so Carth now finally looks at Saul properly instead of making sidelong glances at the player the whole time.

It seems that the dynamic angle 1 shots will randomly switch between from the right or from the left. It seems like before it was almost always from the (speaker's) left, so you'd get the bad angle on the sun, but since the change it seems like from the right is more common, and you can't see the sun at all from that angle. I could add static cameras to take the RNG out of it, but I don't feel like that's really worth the effort.

**Comment by Salk73** [comment]
DP,

while checking on the cutscene I noticed that on the left there is what seems like a destroyed computer station.

Image: https://pasteboard.co/JrdpsDL.jpg

 Do you think that's weird?

**Comment by DarthParametric** [comment]
Presumably that's from Bandon's little display in an earlier scene.

**Comment by Salk73** [comment]
Oh yes, I remember that.

And it's still all broken... Sith efficiency is not what it used to be.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] Needs hide helmets flag.

**Comment by DarthParametric** [comment]
Already fixed in #131.
