### ISSUE TITLE
Leviathan Hangar - Bastila's items are all gone from the inventory but the wielded weapon

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#419]
As reported [here](https://deadlystream.com/topic/8172-kotor-bastilas-equipped-items-after-capture/).

I am not able at the moment to check what happens once Bastila rejoins but I guess all the removed items are back? 

Anyway, there is an inconsistency here: either all items should be removed or none. Personally, I would remove them all.

Opinions?

**Comment by StellarExile** [comment]
I'm not sure if it was intentional or not, but I do agree. Either none or all. I think it's a common problem in the game. I do recall encountering that sometimes party members aren't lootable after their DS demise (Mission, for example).

**Comment by Salk73** [comment]
@JCarter426, @StellarExile and @DarthParametric,  

I have modified the existing k_plev_destweap script so that all items worn by Bastila are returned to the Player's inventory although I'm not sure that is the best solution if it was possible to return them when/if Bastila ever rejoins the party. Would SaveNPCState() perhaps work towards that end?

And if that function won't save the items, would that at least save Bastila's stats so that they can be correctly restored when/if she joins the party again? See #443.

**Comment by JCarter426** [comment]
Yeah, this has been on my list of things to investigate for a while. I hadn't reported it as an issue because when I run into problems in the game that I'm not looking out for, I'm not sure if it was a one-off or repeatable problem. I also can never remember if we fixed Mission's loot, but I don't think we did.

> I have modified the existing k_plev_destweap script so that all items worn by Bastila are returned to the Player's inventory although I'm not sure that is the best solution if it was possible to return them when/if Bastila ever rejoins the party.

I vote for adding all items immediately. It may not make much logical sense, but it's just as logical as stripping Bastila down before the scene to avoid the gameplay annoyance, which is an option. Plus, Bastila's equipment is likely to be outpaced by other items by the time you meet up with her again hours later.

This is also how later BioWare games handle it, as I recall.

> Would SaveNPCState() perhaps work towards that end?
SaveNPCState() isn't called in any source script for either game that we have access to, so I don't know what it does. However, I don't think it would. You lose Bastila's items because she is removed from the party table and, as you have noticed, replaced with a different Bastila when she returns. The only other way to retain Bastila's items would be to keep the same Bastila in the party table until the encounter on the Temple Summit. That doesn't necessitate adding the same Bastila to the party when you get there, but she would have to remain in the party table until then so her equipment could be retained and given back to the player.

**Comment by Salk73** [comment]
JC,

I checked what happens with Mission's items if she is killed on Lehon. The script k_punk_misrem.ncs returns actually all her items to the party using a code very similar to the one I wrote above.

**Comment by DarthParametric** [comment]
Mission, Zaalbar, and Carth's items being returned on Lehon in the DS ending has been addressed in #168. I've got a fix for Bastila on the Leviathan which also allows her to keep her existing equipped weapon throughout the scene rather than equipping a stunt saber, if she already has a saber equipped (which is almost certain).

**Comment by DarthParametric** [comment]
1.9.0 beta test observation:
- [ ] Seems like you can hear Malak's saber deactivating while Carth is talking after Malak and Bastila are off-screen. Might need a revision of the edited scripts, since I added a `CancelCombat` in there. Could possibly just give him a forced saber override and turn it off instantly.
