### ISSUE TITLE
Bastila Star Forge Issues

### ISSUE THREAD

**Issue by StellarExile** [KOTORCommunityPatches/K1_Community_Patch#420]
Spotted by [nt7788](https://www.reddit.com/user/nt7788/).
Apparently Bastila's Star Forge dialogue is all screwed up, she talks to herself. It shows that she is the speaker and listener [here](https://preview.redd.it/zclgpe1q90h31.png?width=2396&format=png&auto=webp&s=ba15b6bde964e309e856abed15ad62afe2c67f71): Additionally, in the scene afterwards, Dodonna is referred to as "CutStart" which I am lead to believe is a standard, sadly.

**Comment by DarthParametric** [comment]
The problem here is stunt Bastila's UserDefine script, specifically the `KOTOR_DEFAULT_EVENT_ON_DAMAGE` that triggers the various stages of the fight/talk/fight/talk sequences:
```
if (nCurHP <= 10 && nGlobal == 3)
	{
		CombatSurrender(oPC);
		DelayCommand(1.0, AssignCommand(GetObjectByTag("sta_bastlast_talk", 0), ActionStartConversation(OBJECT_SELF)));
	}
	else if (nCurHP <= 70 && nGlobal == 2)
		{
			CombatSurrender(oPC);
			DelayCommand(1.0, ActionStartConversation(oPC));
		}
		else if (nCurHP <= 80 && nGlobal == 1)
			{
				CombatSurrender(oPC);
				DelayCommand(1.0, ActionStartConversation(oPC));
			}
			else
				{
					Db_PostString("Current=" + IntToString(nCurHP) + " Bast=" + IntToString(nGlobal), 10, 10, 2.0);
				}
```
Specifically, the last sequence of dialogue (<10HP) is between an invisible placeable (named Bastila) and stunt Bastila, unlike the prior conversations are correctly between stunt Bastila and the PC. This is presumably because you can choose to execute Bastila in this convo, which would break things if she was the DLG owner. Not sure why they didn't imitate it between the placeable and the player though. Interestingly, the DLG is actually almost completely filled out with Speaker/Listener tags, one of the very few examples in the game. However, you can't specify a Speaker tag for response nodes. Normally this defaults to the Player, but it seems like since this is a conversation between the two Bastilas, it's stunt Bastila that is used instead of the Player. Changing the script should fix it, but I don't have a LS save on-hand to test with.

The stunt module ("_There - a break in the Sith formations! Green squadron, move in!_") problem is that the invisible placeable that owns the scene literally has the name "CutStart" (StrRef 40391). I have no idea why they put that in the TLK. Changing the placeable's name to Dodonna will resolve it.

By the way, in future please link directly to the post detailing the issue, not a user profile. Is the Dodonna case also attributable to the same person?

**Comment by StellarExile** [comment]
My apologies. Yes, the Dodonna case is attributable to the same person as well. [Here's the original](https://www.reddit.com/r/kotor/comments/crlqz7/bastila_bug_at_star_forge/)

**Comment by DarthParametric** [comment]
Ah, I didn't notice there's also a line for a pilot. Fortunately there are two "Pilot" StrRefs in the TLK, but we'd have to create a dummy object to hold the name, since DLGs use tags to ID the speaker/listener.
