### ISSUE TITLE
Unknown World Temple - Multiple unlockable doors show Security UI

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#442]
I guess this is very much related to #396 but I opened a new issue just because the other one mentions Taris specifically.

EDIT: I noticed only now that the same thing applies to another door at the Temple Summit: unk44_tpllckdoor.utd

```
[unk44_exitdoor.utd]
!Destination=modules\unk_m44aa.mod
Plot=1
KeyRequired=1
Locked=1

[unk44_tpllckdoor.utd]
!Destination=modules\unk_m44ac.mod
Plot=1
KeyRequired=1
Locked=1
```

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] Seems like the main entrance still has a Security UI.

**Comment by JCarter426** [comment]
I'm reopening this because it sounds like there might be some unintended side effect, according to [this post](https://www.reddit.com/r/kotor/comments/u350we/kotor_1_2_mod_builds_fully_compatible_modular_mod/ipym802/?context=3).

If it's unrelated to this issue, we can close again, but given the nature of the change, this does seem the likely culprit to me.

**Comment by DarthParametric** [comment]
Nah, it would be #325, not due to these changes.
