### ISSUE TITLE
[Unknown World - Temple Summit] Evil Bastila is not her old self

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#443]
It seems like the Bastila you get back is not the same Bastila that left the party.

If the Player has customized her Skills and Feats at Level Up, those choices will be reset and replaced by "default" ones found in the various p_bastila00x.uti files.

That is quite bad but I have also noticed that the items she was wearing, with the exception of her lightsaber, are gone for good (see #419).

It seems I never paid much attention to this in the past but I don't know how it could have escaped me since I find this to be a pretty serious problem.

Can we do something about i?

**Comment by JCarter426** [comment]
I think it's best to leave it for another mod to handle, because every option would result in too much of a change from the original game.

There are two reasons why I imagine things are the way they are.

1. Darth Bastila has a different portrait in the party selection screen. This is is configured on the UTC file, so it's only possible if she is a different object.
2. Darth Bastila has various dark side abilities. K1 has no script functions to grant a character feats or powers, so this is also only possible if she is a different object.

**Comment by Salk73** [comment]
Yes, I think you are right, JC.

It'd be opening a can of worms and the reasons you provided to not touch anything make perfect sense.
