### ISSUE TITLE
War Droid racetex variants seem to override the incorporated blaster texture

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#46]
It appears that racetex variants 2-5 of the War Droid forcibly override the texture for the integrated blaster these droids carry.

![War_Droid_SS_Weapons](https://user-images.githubusercontent.com/46890653/54866708-5e71f980-4dc3-11e9-8499-ca1055f689c2.jpg)

This is the same problem you get when trying to apply a texture variant via appearance.2da to any other model with more than one texture (like a full body model with separate head and body textures). I thought there must be some hard-coded exception for the War Droid, similar to Bao Dur's robo arm in TSL, but apparently not. I guess they never picked it up in QA.

There are three avenues for a fix. The first is to alter the UVs of the model and merge both droid and blaster meshes into a single texture. The second approach is to create separate models for each War Droid variant and edit the appropriate appearance.2da rows to point to these. The third approach is to edit the base model and swap out the incorporated blaster mesh for a reference object, which will pull in an external blaster model, thus exempting it from the texture override. 

The first approach is the least ideal. It would break compatibility with any modded textures for the droids or the blaster. The second approach would be the "standard" way to do it, but it could be vulnerable to 2DA edits and would not support expanded texture variants. The third approach has the benefit of only requiring a single model edit and no appearance.2da changes, making it the most compatible with third-party changes, with the additional added flexibility of now dynamically utilising modded weapons. One downside, however, is that the bullethook is fixed in the droid model itself, which may lead to visual VFX offset issues with modded weapons (albeit a minor issue).

Reported by Sith Holocron in relation to Sithspecter's HQ Blaster mod, but it also happens with the vanilla War Droid models.

**Comment by RedRob41** [comment]
I like the solution that you came up with; to remove the blaster from the model altogether.

My 2048x2048 texture works well enough with your model. Most of the uvw fixes that I made to my model are on barely visible surfaces, like the ends of the upper arm, or the insides of the abdomen. The only one that is clearly visible is the back panel of the upper body/chest where I mirrored the uvws. I did this so that when I look at the texture, it will appear the same way left to right on the actual model (the original makes it backwards). This is no big deal with the vanilla back panels, but if any modder wanted to put some text on there, then they'd have to mirror it on the texture to make it readable in-game. My fixed uvws make it so that the text will be readable on the texture as well as in-game. Other than that there might be some minor uvw shifts so that the HD textures line up better at edge seams; which are only visible with HD textures.
