### ISSUE TITLE
Ebon Hawk - Party can disembark controlling a party member rather than the protagonist

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#466]
Reported by ZeldaTheSwordsman (https://deadlystream.com/topic/4457-k1r-12-impressions-and-bug-reports-read-me-first/page/7/#comments).

I think we should change this so that the Protagonist is always the leader of the party disembarking.

**Comment by DarthParametric** [comment]
I was able to confirm the issue with a brief test. It can be resolved with a minor edit to `k_pebn_exithawk`, which is the exit script for the party selection screen. A simple 
```
	int nSize = GetPartyMemberCount();
	
	if (nSize > 1)
		{
			SetPartyLeader(NPC_PLAYER);
		}
```
appears to resolve it.

Naturally, Bioware gonna Bioware, so the three different Hawk modules all use the same script name with different contents. Fortunately though the `ebo_m12aa` version covers the post-Leviathan and Lehon variants. Since everything is determined by a check of `K_CURRENT_PLANET`, they can be safely overwritten with a single version of the script.

**Comment by Salk73** [comment]
Sounds good to me.

Just a small off topic, DP. Is there any official release plan for K1 CP 1.9? I know there are some outstanding open issues that should be taken care of but the current version is already a huge improvement over 1.8. Are there any major blockers?

**Comment by DarthParametric** [comment]
Maybe by Xmas, if I get around to it.

**Comment by Salk73** [comment]
Well, I guess it's just a matter of adding:

```
  if (GetGlobalBoolean("K_AT_EBON_HAWK"))
  {
    SetGlobalBoolean("K_AT_EBON_HAWK", FALSE);
  }
```
