### ISSUE TITLE
Taris Undercity - Meeting Mission

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#472]
There are issues if the party leader is not the Player.

The script _k_ptar_miscrt_en_ needs to switch party leader for the cutscene to work properly.

**Comment by DarthParametric** [comment]
It does lead to some amusing pirouettes by the player if Carth is party leader. Should probably take this opportunity to jump the party into position.

**Comment by DarthParametric** [comment]
Additional issues: 

- Since the trigger is an inverted horse shoe shape, you can trigger the scene from multiple positions. Going to the right, towards the Sith officer, results in Mission having to run a long way from her spawn point behind some rubble. Jumping the party to somewhere in the middle will mitigate that somewhat.
- When Mission is added to the party, the stunt Mission being destroyed and party Mission being spawned in clearly visible. Needs to be done under a fadeout.
