### ISSUE TITLE
Cannot find file: "...\k_swg_helena01.utp"

### ISSUE THREAD

**Issue by JediCat** [KOTORCommunityPatches/K1_Community_Patch#475]
When running the 1.81 INSTALL.exe, the TSLPatcher runs into an error as follows: 

...
 [Install] 	Adding file "k_swg_helena01.utp" to archive "tat_m18ac.mod"...
 [Install] 	GFF Check: 8_Backing up the file: C:\Users\-user-\Downloads\Com Patch\tslpatchdata\k_swg_helena01.utp to C:\Users\-user-\Downloads\Com Patch\tslpatchdata\erfpatch_temp\k_swg_helena01.utp..
 [Error] 	Cannot open file "C:\Users\-user-\Downloads\Com Patch\tslpatchdata\k_swg_helena01.utp". The system cannot find the file specified (EXT-0)

See attached installlog.txt

Steps to reproduce:
1. Download the zip file to install the mod/patch.
2. Extract.
3. Run the INSTALL.exe
[installlog.txt](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/7361637/installlog.txt)

**Comment by DarthParametric** [comment]
It's a problem on your end. Extract the archive somewhere else, closer to the root of the drive and preferably not on C drive at all.

**Comment by DarthParametric** [comment]
This is a problem on your end, not a problem with the mod itself (it works fine for everyone else). I see that your game is installed in Program Files, which is never a good idea.  Windows is finicky about permissions there. I'd advise Googling about how to create Steam Libraries in other locations and migrating already installed games.

Since you are using Steam, go into the game's folder and delete the Override and Modules folders. Then in Steam right click on the game's entry in the Library list and go to Properties -> Local Files -> Verify Integrity of Game Files. This will return the game to a virgin state. You should do this after any failed install. Do not try reinstalling mods multiple times. Once that is done, try running the installer with administrator privileges.

**Comment by JediCat** [comment]
I tried as you suggested, using a fresh install of KoTOR, and a fresh download & extract of the patch, inside my D drive. The patch worked without issue.

Thank you for your assistance, apologies if my issue came off as annoying/rude/etc. May I suggest adding this tip to either Installation instructions or Compatibility/Known Issues? It's not the most intuitive fix, even for someone with decent computer skills, and would save time when starting a lengthy/sizable mod package.

Thanks again!
