### ISSUE TITLE
Taris Lower City - Bek door guard doesn't reface correctly post-combat

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#498]
1.9.0 beta test observations:
- [x] Apparently the Bek guard will help out in combat against Vulkar mooks if they get close enough. She has a return to base script it would seem, which sends her back to her door post, but she doesn't reorient afterwards, leaving her facing whatever way she was walking.

**Comment by DarthParametric** [comment]
- [ ] Also needs to be refaced at the end of conversation.

**Comment by LaIngobernable** [comment]
She's also positioned in such a way that in certain animations when talking her face and neck will go darker as in shade, while this change in lighting isn't reflected on her clothes. It's most likely because the particular spot she's at is in a well lit area, but also right next to a poorly lit area. Not the clearest of issues, considering her dark skin.
