### ISSUE TITLE
The rancor cages on the Unknown World are still bugged

### ISSUE THREAD

**Issue by LtFrankDrebin** [KOTORCommunityPatches/K1_Community_Patch#561]
Hello. I already reported this bug several months ago: https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/473 I've tested the latest update 1.9 today, and unfortunately the cutscene where the player confronts The One in the western compound still doesn't work as intended. As before, the rancors cannot leave their cages and attack the player after The One pulls the lever that is supposed to control the gates to the rancor cages. I tested it using a plain vanilla game with nothing but the latest version of Community Patch installed on top of it.

P. S. There's another issue that I've encountered while testing this update: during the dialogue with a Duros miner at the beach on the Unknown World, when the camera faces the Duros interlocutor, all textures disappear and then reappear again when the camera turns back towards the player: https://i.imgur.com/YyR2ZOZ.jpg

**Comment by DarthParametric** [comment]
In future please do not open a new issue when there's already an existing issue for a problem. Even though #473 is closed you can still add new comments.

I'm not sure how this problem is happening. It seems like it might be some inconsistent behaviour in the script possibly. There should be only one route to that hostile ending from what I can see. Download and extract the attached zip, and put the DLG in your Override. See if it still happens.  [unk43_theone.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/7761789/unk43_theone.zip)

As to the Duros, that's a missing static camera issue, but it's the same camera used for every Duros line. I don't have that problem here. That line (and all their other lines) works fine for me.

**Comment by LtFrankDrebin** [comment]
Thank you for that zip file, the cutscene finally works correctly (the lever has an animation of being pulled to the side, and the rancors are released), Sorry for the double post, I didn't know I could reply to closed threads, I thought they would be fully archived, At least that rancor issue has been fixed.

As for the Duros cutscene texture bug, it happens intermittenly: I encountered it on a vanilla build + Community Patch 1.9, but if I add my other mods and load my older savegames, all of the textures are correctly displayed throughout that dialogue section.
