### ISSUE TITLE
Manaan Sith Base - Shasa has a challenge rating of 0.33

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#573]
Sasha, the Selkath turned Sith in the Sith Base, has a challenge rating of 0.33 whereas her Selkath allies all have a challenge rating of 6.

I'm not sure what the challenge rating does in terms of gameplay, but I suspect the CR (at minimum) affects how much experience the player will receive when the enemy is defeated. As her CR is 0.33, I again suspect she gives no XP upon killing her.

**Comment by DarthParametric** [comment]
Technically it's _Shasa_. Sasha is the midget stowaway on the Ebon Hawk.

Yes, CR affects XP earned. Since it is such an aberration from the others, I would suggest that this was probably deliberate, since you were sent there to save her, not kill her. But testing it with a PC at level 15, the difference was 20XP for Shasa vs 50XP for the Selkath mooks which is completely inconsequential in the greater scheme of things. Changing it is hardly worth the bother.
