### ISSUE TITLE
GenoHaradan or Genoharadan?

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#574]
Various text throughout the game calls it "GenoHaradan" whilst others call it "Genoharadan" without a capitalized "H".

Since the Wookieepedia and TOR subtitles refer to the organization as "GenoHaradan" we can justify converting all mentions of "Genoharadan" to "GenoHaradan".

**Comment by Salk73** [comment]
I believe stylistic text correction don't pertain the K1 CP domain.

The change you suggested is something I have already made locally quite some time ago. I believe other modders' dialog.tlk replacement files include it as well.

**Comment by th3w1zard1** [comment]
Could someone explain why this isn't considered a bug? It's labeled 'For Standalone Mod' as it's outside the scope of this patch. What is the Community Patch for, if not to fix typos and bugs in the vanilla game? Thanks.

**Comment by DarthParametric** [comment]
Since TSLPatcher doesn't have the ability to edit TLK lines, only add new ones, all spelling and grammatical fixes were left to third party TLK replacement mods to fix. With the suggested changes to PyKotor, our stance on this may change in the future once a full transition to HoloPatcher is viable.

See also #148.
