### ISSUE TITLE
Taris Lower City Javyar's Cantina - Placeable sitters use wrong appearance

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#586]
In the Lower City Cantina "tar_m03ae" exists two placeables, "sitswoopg001.utp" and "sitswoopg002.utc".

The 1st placeable is set to the appearance "SittingSwoopganger" (Nikto Black Vulkar) and in-game it is simply sitting down doing nothing. "sitswoopg002.utc" on the other hand is doing the Pazaak animation and the file name would suggest that the 1st sitting Swoop Ganger placeable is meant to idly sit whereas the 2nd sitting Swoop Ganger placeable is playing Pazaak.

The problem is that "sitswoopg002.utc", despite strongly suggesting it was intended to be the Black Vulkar "SittingSwoopganger" appearance, is actually using the "SittingRodian" appearance instead.

A very minor problem I only noticed when I was specifically digging through the files for one of my mod updates, I figured I might as well report it here.

**Comment by DarthParametric** [comment]
After looking at the module, I'm not sure there's any actual issue here. Both sitswoopg001.utp and sitswoopg002.utp share the same tag, `ptar_sitter`, which means they both get assigned the same animation, ANIMATION_PLACEABLE_ANIMLOOP01`, by the module OnEnter. There is a sitrodian001.utp which has the tag `ptar_pazplayer` and thus gets assigned `ANIMATION_PLACEABLE_ANIMLOOP03`. 

As to appearances, you cannot ever infer anything simply from ResRefs. Although less common than it is in TSL, there are clearly many cases where the designer simply duplicated an existing asset and didn't bother to change the ResRef to something more meaningful/representative despite making changes to appearance, etc.
