### ISSUE TITLE
Taris Hideout - The transition between Bastila's conversations could be smoother

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#603]
After bringing Bastila to the hideout to meet with Carth, the second conversation that follows, in which the PC tells her about their visions, starts a little abruptly. A brief moment with the camera pointing at Bastila in a listen animation would make the transition smoother, TSLRCM style.

Let me know if this is input overload, by the way. It's kinda hard to check whether an issue is a duplicate, or to know whether a suggestion is beyond the scope of K1CP.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
It's something that's perpetually on my to-do list when beta testing, but I apparently never got around to adding an issue for it. That convo is fired by a trigger, possibly due to a different structure to events in an earlier version of the game. I believe I have proposed simply appending the vision conversation to the end of the post-swoop race Carth-Bastila DLG when discussing it on Discord it in the past. That would remove the switch between DLGs, but wouldn't really change the abrupt segue. 

> It's kinda hard to check whether an issue is a duplicate

Easy. You just need to memorise all 600+ issues.

**Comment by DarthParametric** [comment]
I think the easiest solution is to change the Bastila vs Revan fight video (02.bik) from where it is now, covering the load between the Swoop Platform to Hideout module transition. Instead it can be played between the existing two convos. I suspect that might have been the original intent anyway given the fact that the sequence is split in two and Bastila's `Is... is something wrong?` indicates that it's not something that was affecting the PC previously. They likely just moved the video because load times were significantly longer on the Xbox. 

The StrRef for the player's response would need to be changed from the current `Something weird happened when we first met. Like a vision.` to `Something weird just happened. Like a vision.`
