### ISSUE TITLE
Leviathan Hangar - Red panel behind Bastila during Malak convo

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#637]
Something's going on with the red panel behind Bastila that's visible during her interventions after the reveal cutscene. There's a patch of something that looks like the force field used in the hangar. It's purple and flickers a bit.

**Comment by LaIngobernable** [comment]
There you go. Curiously, the first time I tried to capture it the cameras used a wider shot instead of the close-up.

![redpanel](https://user-images.githubusercontent.com/84716163/175076165-4a5016f7-dbdf-4152-adb6-d30314e8e3b6.png)

**Comment by DarthParametric** [comment]
The cameras are dynamic, so the shots will vary slightly every time.

The issue is a hairline gap in the geometry. The hallway is actually blackboxed specifically to prevent this kind of thing, but the problem is this bit is right on the corner of the intersection, so you can see past the black box. The room model will need some minor adjustment.
