### ISSUE TITLE
You can ask Jolee about Sunry even if he hasn't talked to Elora or his messenger

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#641]
I basically skipped the quest: I triggered Elora's convo without Jolee in the party and told her to get lost and never brought Jolee to talk to her, neither did Jolee talk to his old pal. Even so, I can ask Jolee about Sunry, when supposedly this is the first news he's heard about him. His response doesn't make sense this way.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
R40 - "Tell me about Sunry. How do you know him?" - is gated by the starting conditional [k_swg_jolee18](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Data/scripts.bif/k_swg_jolee18.nss). Since global number `MAN_MURDER_PLOT` is set to 1 when Elora is first spawned by the module's OnEnter, this branch will become available as soon as the player sets foot in Ahto West for the first time, regardless of other factors. 

I can't find any case of the global being set to 2, so the last check could never evaluate true. Presumably that would mean that you could repeatedly ask Jolee about Sunry while the global is still set to 1, despite it being intended to be gated off by setting `SW_PLOT_BOOLEAN_06` on him the first time.
