### ISSUE TITLE
Korriban Valley of Dark Lords - One of Calo Nord's thugs plays ambient animations during conversation

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#645]
One of the Sith soldiers that ambushes you with Calo insists on doing random NPC animations behind him while he's talking, and eventually wanders off, to the point of not joining the fight.

**Comment by DarthParametric** [comment]
I've never encountered him there, but looking at the UTCs it seems that the problem is one of the Troopers was assigned the wrong OnSpawn script. The working one gets `k_kor_ambmobx`, while the other gets `k_pkor_spn_dynam` which sets the flag `SW_FLAG_AMBIENT_ANIMATIONS_MOBILE` that the former lacks.

The two Bandon mooks have `k_pkor_spn_dy2x2` as their OnSpawn which is functionally identical to `k_kor_ambmobx`. The latter additionally contains `GN_SetDayNightPresence(AMBIENT_PRESENCE_ALWAYS_PRESENT)`, but that function was removed so it does nothing.
