### ISSUE TITLE
Dantooine Enclave - Merchant Crattis Yurkal's offer

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#658]
Hinted by JC to be a case of bad coding, most likely. This is not restored content: you can be given the merchant's offer to sell cave crystals in vanilla, though it is very easy to miss, since once you pass the test to be a Padawan his new greeting overrides the offer (or something to that extent).

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
This is controlled by the starting conditional `k_pdan_jedi08`. Since it is a global script, the original Bioware comments remain intact and thus we know exactly what the designer intent was:
```
    Checks to see if DAN_JEDI_PLOT is 4 (meaning that the
    player has successfully cleansed the grove) and
    DAN_CRATISL_DONE is FALSE (meaning that Crattis has
    not yet offered to buy lightsaber crystals off the
    player). This conversation will not repeat since
    DAN_CRATISL_DONE is set to TRUE to show that this
    conversation has taken place.
```
We could change `GetGlobalNumber("DAN_JEDI_PLOT") == 4` to `GetGlobalNumber("DAN_JEDI_PLOT") >= 4` so that it is still available after you've advanced the main plot to/beyond the star map. But it is clear it is only meant to be a one-time offer.
