### ISSUE TITLE
Leviathan Prison Block - Force fields sound not working

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#660]
We need to enable the looping flag in the forcefield.uts file used in the lev_m40aa module (currently set to 0).

```
[lev_m40aa_lev_forcefield.uts]
!Destination=modules\lev_m40aa.mod
!Filename=forcefield.uts
Looping=1
```

**Comment by DarthParametric** [comment]
Not the entire solution. They also need `Continuous` set to 0 (that was the flag they were using instead of looping) and the four cell door UTDs need the addition of an OnClosed script that restarts the UTS for Mission and Jolee's starting cutscene (to complement the existing OnOpened that turns it off).

**Comment by Salk73** [comment]
Right. I leave this in your capable hands.
