### ISSUE TITLE
Taris Lower Apartments - Black Vulkars Encounters 

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#662]
I'm not exactly sure about how the .UTE files work but I noticed that both the apartment modules in Lower Taris (tar_m03ab and tar_m03ad) use the same resources for spawning Black Vulkars inside: g_blackvulkar001 and g_blackvulkar002.

When I enter the tar_m03ab module it seems two identical Twi'lek are spawned as part of one such encounter. I think they come from the g_blackvulkar001 group and here is what I am not sure about the spawning mechanics with encounters. That .UTE file contains three UTC and one of them has the Twi'lek appearance while the other two the much more appropriate SwoopGang appearance. I don't know how but the game can spawn two of the same .UTC rather than different ones at times.

Could we possibly try and avoid having two identical Vulkar being spawned? And possibly, could we just change the appearance of the Twi'lek (tar03_blackv038.utc) with a non used SwoopGang UTC (Appearance 263)?

**Comment by DarthParametric** [comment]
In both cases the GITs specify three encounters, with tar_m03ab having two instances of g_blckvulgrou001 and one instance of g_blckvulgrou002, while tar_m03ad has three instances of g_blckvulgrou001. In all cases the encounters are set to spawn a minimum of two and maximum of three creatures. I'm unsure whether the creature selections are completely random or are chosen sequentially. It would require testing. That aside, changing appearances would be possible although I don't really see any significant issues with Twi'leks. A mix of Nikto, Twi'leks, Rodians, and Aqualish would be best.

Interestingly, it seems that tar_m03ab's encounters are flagged as continuous, while tar_m03ad's are flagged as one-shot. I don't recall if I have ever noticed that, since I'm not in the habit of returning to tar_m03ab. Whereas you have to come back to tar_m03ad at least once if you choose to help out Matrik. Possibly why those ones are one-shot.

**Comment by Salk73** [comment]
From what I can see, the g_blckvulgrou001.ute file used in both modules is the same.

**Comment by DarthParametric** [comment]
It's g_blackvulkar002 that is flagged as having infinite respawns. You're correct that g_blackvulkar001 is identical in both modules.
