### ISSUE TITLE
Taris Undercity - Wounded Republic Soldier's animation

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#666]
Another very minor issue.

- [x] The infected Republic Soldier in Taris Undercity correctly shows the injured animation when he's spawned but it doesn't keep it after he starts talking to the party. Ideally he should instead continue showing the injured animation until he is cured or until he turns into a rakghoul.

Edit: Added additional issues - DP

- [x] When giving the serum to the soldier, he does the inject anim before the player can reach him.
- [x] When giving the serum to the soldier, as he runs off after hearing a noise the party doesn't turn to look at him.
- [x] When giving the serum to the soldier, not all the Rakghouls attack before he dies.

**Comment by DarthParametric** [comment]
This can make use of the same additions JC made for Handon in #38.

**Comment by DarthParametric** [comment]
The anim is initiated by the soldier's [UserDefine](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M04AA_Taris_Undercity_tar_m04aa/k_ptar_repsol_ud.nss) script. So he will start playing the anim on his first heartbeat tick after spawning. However, since the function then sets the local boolean to true, it won't reinitiate on subsequent ticks. He gets a TALK_INJURED anim on the first node of the DLG, but none of the subsequent ones it would seem. Judging by the empty `k_ptar_repstand` script on E4, it would appear the original intention was to clear the anim when given the serum. I'll have to test what happens in that scenario, since I don't recall giving him the serum in recent playthroughs. When not giving him the serum he gets hit with `EffectHorrified` via [`k_ptar_repvic`](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M04AA_Taris_Undercity_tar_m04aa/k_ptar_repvic.nss) before the change to a Rakghoul.

I'll have to play through it to see what normally happens with him. I assume the first node in-DLG anim is nuking the scripted anim, so the fix might be as simple as removing that.
