### ISSUE TITLE
Korriban Dreshdae - Lurze dialog is missing one persuade check

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#676]
Fix:

```
[ebo46_lurze.dlg]
!Destination=modules\korr_m33aa.mod
ReplyList\46\EntriesList\38\Active=k_con_persmed
```

**Comment by DarthParametric** [comment]
One could also make the argument that the Force Persuade (R51) that is nested under the failure branch of the persuade should also have a copy added to the root of E15 so it can be chosen directly. Also, the FP is only a low requirement check (i.e. only requires Affect Mind, not Dominate). Interestingly, it uses a local version of the k_con_fperslow script that only does a `GetHasSpell(FORCE_POWER_AFFECT_MIND, GetPCSpeaker())` check vs the global script doing a `GetHasSpell(FORCE_POWER_AFFECT_MIND, GetPCSpeaker()) || GetHasSpell(FORCE_POWER_DOMINATE, GetPCSpeaker())` check. I suppose that should be irrelevant though, since taking the former is a requirement for taking the latter.

**Comment by Salk73** [comment]
Yes, the Force Persuade could be offered together with the Persuade option but I think it's fine to leave it like it is.

**Comment by DarthParametric** [comment]
The change should actually be `ReplyList\46\EntriesList\0\Active=k_con_persmed` according to ChangeEdit.
