### ISSUE TITLE
Bastila's low-res slave outfit

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#677]
If the player equips Bastila with a Dark Robe and then remove the robe instead of her default underwear she will be wearing her slave outfit from the Taris Swoop track, however, upon closer inspection it turns out this specific dark side underwear texture is a different texture from the one she has during the Taris Swoop track encounter.

The texture used in the Taris Swoop track encounter is called "P_BastilaBAS01" which is a 512x512 in resolution.

The texture used when accessing the slave outfit easter egg is "P_BastilaBA02" which is a lower resolution 256x256.

The solution to this issue would be to take "P_BastilaBAS01" and rename it to "P_BastilaBA02", this will keep the easter egg slave outfit and the real slave outfit textures consistent with each other.

**Comment by DarthParametric** [comment]
It's not an "Easter egg" so much as a bug. The engine is simply "remembering" that it was previously using the 02 texture variant when you unequip an 02 texture variant robe. Since the slave texture exists as an 02 underwear texture variant, it loads that. Note that it doesn't happen when unequipping any of the Dark Jedi/Knight/Master 05 robes, since they use texture variant 04, not 02. If you give Bastila armour proficiencies then it will also happening when unequipping any armour that uses an 02 texture variant. Throw an 02 underwear variant into the override for the player or any other party member and you'll see the same behaviour for them as well. 

The appropriate fix is to rename a copy of P_BastilaBA01 to P_BastilaBA02.
