### ISSUE TITLE
Kashyyyk Great Walkway - Dark Jedi doesn't drop datapad

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#689]
The leader Dark Jedi trios are supposed to drop a datapad, this works as intended on Tatooine but on Kashyyyk the datapad item isn't set to drop so the player never gets their hand on it.

The Tatooine datapad tag is "tat17_datapad" whilst the Kashyyyk datapad is "kas22_datapad", the difference between these two datapads is that the Tatooine datapad has an extended description so we'd either have to copy the Tatooine text to the Kashyyyk datapad or we'd simply swap out the Kashyyyk datapad with the Tatooine datapad on the Kashyyyk Dark Jedi and set it to drop.

I can foresee two problems that could arise from a possible fix of this bug, if the Kashyyyk Dark Jedi drops the Tatooine datapad the item will stack in the player's inventory whereas the Kashyyyk datapad would be considered a different item from the datapad obtained on Tatooine.

And the second problem is that these datapads are considered plot items meaning if we do give the Kashyyyk Dark Jedi a datapad it'll result in the player having two identical datapads permanently, this can be avoided if we deactivate the plot item flag allowing the player to sell the datapads to a merchant or place them in a Footlocker to get rid of them.

**Comment by DarthParametric** [comment]
Easy enough to set the droppable flag in the Dark Jedi's UTC and change the description StrRef in the datapad UTI. 

While we are at it, we could change both the Tatooine and Kashyyyk datapad name StrRefs to 15146 (`Sith Datapad`) or add a new custom one, perhaps `Dark Jedi Datapad`. 

Alternatively, there are four existing StrRefs that are simply `Datapad` - 540, 5773, 15144, 41724 - that could be checked to see if any are unique or unused (both these datapads currently use 5773). If so, they could be edited/overwritten instead of adding a new StrRef given the mod's switch to HoloPatcher.

I don't see any need to remove the plot flag.
