### ISSUE TITLE
Leviathan Prison Block - Player can leave the underwater suit behind

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#698]
Apparently, it is possible to lose water suits permanently if one is captured by the _Leviathan_ before completing Manaan and then never collects the party's inventory.

It looks like the plot flag is already checked and the stolen flag is not checked, but even if those don't work, it should be possible to hard-code the item to not be stolen by editing the inventory theft script. Alternatively, we could perhaps make the water suit respawn on Manaan if it is not in your inventory.

This is kind of brought-it-on-yourself territory, but I think it would be prudent to make it possible to at least complete the game.

**Comment by DarthParametric** [comment]
Well that's certainly one hell of an edge case, progressing Manaan far enough to explore Hrakert Station to the point of picking up the suit but backtracking before going out into the Rift and then doing a whole other planet first. Doesn't look like a global is set for [picking the underwater suit up](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Data/scripts.bif/k_pman_suituse.nss). The airlock door conversation simply [checks for it](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Data/scripts.bif/k_pman_airlock01.nss) in your inventory. 

As a related aside, it seems like the original intention was to set a global for picking up the spacesuit (global boolean `LEV_SPACESUIT`), since there's what appears to be a placeable OnUsed script setting it true in both the [Command Deck](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M40AB_Leviathan_Command_Deck_lev_m40ab/k_plev_getsuit.nss) and [Bridge](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M40AD_Leviathan_Bridge_lev_m40ad/k_plev_getsuit.nss) modules, but both are unused/not attached to anything. The suit placeable uses [this script](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M40AB_Leviathan_Command_Deck_lev_m40ab/k_plev_givesuit.nss) instead and the airlock does a similar item in inventory check. Although the global is used in a number of other scripts while doing the spacewalk. I can't see any obvious equivalent underwater suit global/s.

The most practical course of action would be to check the locker for the suit during the post-breakout cutscene and automatically add it back to the player's inventory. Should probably also add back any other plot-related items while we're at it I guess.
