### ISSUE TITLE
Tatooine and Kashyyyk – Final Star Map Animation Timing Issues

### ISSUE THREAD

**Issue by WildKarrde1138** [KOTORCommunityPatches/K1_Community_Patch#756]
The utility function UT_StarMap4RunStarMap(), which is called to play most of the Star Maps, includes a 60 second delay between opening and closing the final map to allow the more elaborate final animation to play out exactly once.  However, on Tatooine and Kashyyyk, I have observed cases where the timing is off and the closes partway through a second animation loop.   If the diagram of the Star Forge system is showing when it closes, the star does not disappear but continues to show even after the map has shut down:
![Bugged Star Map Animation](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/142758114/5a0f01d7-45be-4841-a890-ec125458dbc4)

The issue seems to be related to the party’s reaction dialog:  If I click through it fast enough, the animation timing works as it should.  Based on some experimenting, it appears that the animation timing doesn’t track properly when the map is not on screen during the dialog.  That would also explain why I have never noticed the issue on Korriban, where there is no party to interject.  Unfortunately, if that’s the case, I’m not sure of a way to fix it short of using custom camera angles so that the map is always in view.

**Comment by DarthParametric** [comment]
Hrm, odd. Could possibly be avoided by signalling an invisible placeable to fire the anim rather than from in the DLG itself. Although I would have thought the DLG owner in both cases was already an invisible placeable.

I know I have edited the Kashyyyk anim before because it was closing too early (see #123). Might be some issue with those changes perhaps. Can't recall if something similar was done on Tatooine, although I know the party was jumped for the scene at the very least.

**Comment by DarthParametric** [comment]
> account for the length of the opening animation

You don't need to account for that anim. The function adds the new animation to the placeable's action stack (via `ActionPlayAnimation`), so it will fire once the open anim is finished.

> it still ends with the star hanging in place after the map closes

It may not be something that is fixable. Although maybe the anims themselves could be edited.

**Comment by DarthParametric** [comment]
`DelayCommand` delays when the stated function fires, but it's firing `ActionPlayAnimation`, so it gets added to the action stack.

**Comment by DarthParametric** [comment]
OK so testing this out on the Tatooine map by setting the `K_TAT_STAR_MAP` global to 40, I get the same issue where it cycles into a second loop of the anim and then closes halfway through. I guess because it's a loop it will just play endlessly until it gets another command. This is the same issue JC pointed out in #123, although the fix there wasn't correct, since setting the delay to double the length of the anim just makes it play twice, which looks weird. I think the problem in Kashyyyk's case was that that a single loop ended too soon, so the anim was over by the time Jolee finished yapping. Since I want to address the two separate DLGs there at some point anyway, we can probably add a shot that shows the full anim if it's the last map. I guess we could do the same for the other maps as well, since they're all handled in DLGs.

**Comment by DarthParametric** [comment]
One other thing to note is that the deactivate anim doesn't really work well with the final map's anim, since it briefly pops the initial outer sphere elements. Not sure if anything can be done about that, since altering the anim would affect all the others. It could be added as a new animloop I guess, since there's provision for up to 10, but you'd have to do a `ClearAllActions` on it right after to stop it looping.

**Comment by DarthParametric** [comment]
The sound is proving extremely flaky. The inbuilt placeable sounds don't always fire, and even adding custom sound objects and telling them to play doesn't always work. Seems like enabling the "Sound Exists" flag on a DLG node helps with getting `PlaySound` to work, although it appears dialogue firing at the same time can interfere with it. It's difficult to tell for sure on Tatooine because of all the random background stuff going on.

**Comment by DarthParametric** [comment]
Might as well extend these changes to the Korriban map as well.

**Comment by DarthParametric** [comment]
1.10.0 beta test 2 observations:

- [ ] The Tatooine map sequence needs to be further adjusted to match the setups for Manaan/Kashyyyk/Korriban.
