### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by NeverluckySMILE** [KOTORCommunityPatches/K1_Community_Patch#781]
windows defender and virustotal are saying the installer is a trojan

**Comment by DarthParametric** [comment]
It's a false-positive due to the way Python works as a self-contained exe on Windows (Google PyInstaller for more info). But Defender shouldn't flag it if the definitions are up to date. A false-positive report was filed with MS over Christmas and VirusTotal only shows a handful of obscure AV packages still flagging it.

https://www.virustotal.com/gui/file/5cc9fc7aeafefb8b18cd584de0ad530f5c7a057e4b0a1308ed7bc6a9e4bc3fbe
