### ISSUE TITLE
Stealth during post-Leviathan sequence

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#9]
If anyone is stealthed during the end of Leviathan, at the post-Leviathan scene it freezes the dialogue, or glitches because they haven't come back out of stealth mode.

**Comment by DarthParametric** [comment]
Seems like firing a script to ClearAllEffects at some point before the conversation kicks off should fix this.

**Comment by DarthParametric** [comment]
After testing various scenarios, I am still unable to replicate this bug. It seems like it shouldn't be possible, as interacting with a computer terminal forcibly de-stealths the character. This will require more detailed information from someone that has experienced the bug.

**Comment by DarthParametric** [comment]
Through some save file editing I have managed to replicate the symptom, although the cause still eludes me. A workaround has been developed that will allow the scene to proceed, albeit with the stealthed companion still remaining in stealth throughout the conversation (and apparently missing until the next party selection on exiting the Ebon Hawk).

**Comment by JCarter426** [comment]
[cp_lev_awarefix.txt](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/2798248/cp_lev_awarefix.txt)
This code should give the player and Carth fixed awareness boosts. The point was to prevent it from rolling over the maximum score, but I don't know if that's necessary anymore because once I tested it, I noticed skills have a cap of 30 + WIS modifier anyway.

**Comment by DarthParametric** [comment]
So I just tested this again and interestingly the fix **_did not_** work. However, I did find a working fix, a left-over from NWN: `EffectTrueSeeing()`.
