### ISSUE TITLE
Manaan Hrakert Kolto Control - Scientists attack with fists

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#94]
The two surviving scientists in the Hrakert facility (manm28ac) have their weapons equipped for the duration of the encounter. They only have weapons in the event that you choose to kill them, so it's jarring for light-sided players - especially when the woman does the pleading animation while gripping a blaster.

**Comment by DarthParametric** [comment]
Given removing the equipped weapons via editing the UTCs would presumably require a hard replacement due to TSLPatcher's inability to delete structs, maybe the best approach would be to script an `ActionUnequipItem` on them in the module OnEnter? Then hijack k_pman_sur13 (won't decompile - from the bytecode it looks like a full AI script) on Reply 70 to have them reequip.

**Comment by JCarter426** [comment]
Or through their individual OnSpawn scripts, yeah.

**Comment by DarthParametric** [comment]
On doing some other edits to the Kolto Control module, I noticed this fix used a script hijack approach due to the original not decompiling (Manaan include `GetStringByStrRef` issue). Now that is no longer a problem, we can merge this fix into a single combined script.
